Foreground yes
LogTime yes
TCPSocket 3310
TCPAddr 0.0.0.0
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /work
MaxThreads 1
MaxQueue 8
StreamMaxLength 1900M
MaxFileSize 1900M
MaxScanSize 2000M
MaxFiles 2000
MaxRecursion 10
MaxScanTime 180000
ReadTimeout 30
CommandReadTimeout 10
ScanArchive yes
ScanPDF yes
ScanOLE2 yes
ScanHTML yes
ScanPE yes
HeuristicAlerts yes
AlertExceedsMax yes
AlertEncrypted yes
ExitOnOOM yes
Bytecode yes
BytecodeSecurity TrustSigned
